name: publish 

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version of the image in semver format.(e.g. v0.0.1).'
        required: true
  push:
    branches:
      - main
    tags:
      - v*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: pablochacin/kwok

jobs:
  publish-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: get-version
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
              IMAGE_VERSION="${{ github.event.inputs.version }}"
          elif [[ "$GITHUB_REF_TYPE" == "tag" ]]; then
              IMAGE_VERSION=$GITHUB_REF_NAME
          else
              IMAGE_VERSION="latest"
          fi
          echo "IMAGE_VERSION=$IMAGE_VERSION" >> $GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up buildx
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.9.1
      - name: Log into ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        env:
          IMAGE_VERSION: ${{ env.IMAGE_VERSION }}
        run: |
          IMAGE_TAG="$REGISTRY/$IMAGE_NAME:${IMAGE_VERSION:-latest}"
          docker buildx build -t $IMAGE_TAG --platform=linux/amd64,linux/arm64 . --push
